services:
  backend:
    build:
      target: production
    env_file:
      - path: ./luvhavencove-store/.env.production
        required: false
    environment:
      - NODE_ENV=production
  storefront:
    env_file:
      - path: ./luvhavencove-store-storefront/.env.production
        required: false
    environment:
      - NODE_ENV=production
  postgres:
    volumes:
      - ./.production/data:/var/lib/postgresql/data
secrets:
  meilisearch_master_key:
    file: ./secrets/production/meilisearch_master_key
  paypal_client_secret:
    file: ./secrets/production/paypal_client_secret
  postgres_pass:
    file: ./secrets/production/postgres_pass
  redis.conf:
    file: ./secrets/production/redis.conf
