services:
  certbot:
    depends_on:
      - nginx
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-var:/var/lib/letsencrypt
      - webroot:/var/www/_letsencrypt
      - nginx:/etc/nginx
    command: >
      certonly -a dns-cloudflare -i nginx --dns-cloudflare-credentials /run/secrets/cloudflare_api_token -d $DOMAIN -d www.$DOMAIN -d api.$DOMAIN -d admin.$DOMAIN
    secrets:
      - cloudflare_api_token
  cloudflare-ddns:
    depends_on:
      nginx:
        condition: service_healthy
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    read_only: true
    cap_drop:
      - all
    security_opt:
      - no-new-privileges=true
    environment:
      - CF_API_TOKEN=/run/secrets/cloudflare_api_token
      - DOMAINS=$DOMAIN,www.$DOMAIN,api.$DOMAIN,admin.$DOMAIN
      - PROXIED=true
    secrets:
      - cloudflare_api_token
secrets:
  cloudflare_api_token:
    file: ./secrets/production/cloudflare_api_token.ini
  meilisearch_master_key:
    file: ./secrets/production/meilisearch_master_key
  paypal_client_id:
    file: ./secrets/production/paypal_client_id
  paypal_client_secret:
    file: ./secrets/production/paypal_client_secret
  paypal_auth_webhook_id:
    file: ./secrets/production/paypal_auth_webhook_id
  postgres_pass:
    file: ./secrets/production/postgres_pass
  redis.conf:
    file: ./secrets/production/redis.conf
