services:
  certbot:
    depends_on:
      - nginx
    build:
      context: ./certbot
      dockerfile: Dockerfile
    environment:
      - DOMAIN=$DOMAIN
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-var:/var/lib/letsencrypt
      - webroot:/var/www/_letsencrypt
      - nginx:/etc/nginx
    secrets:
      - cloudflare_api_token.ini
  cloudflare-ddns:
    depends_on:
      nginx:
        condition: service_healthy
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    read_only: true
    cap_drop:
      - all
    security_opt:
      - no-new-privileges=true
    environment:
      - CF_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - DOMAINS=$DOMAIN,www.$DOMAIN,api.$DOMAIN,admin.$DOMAIN
      - PROXIED=true
      - IP6_PROVIDER=none
    secrets:
      - cloudflare_api_token.ini
  backend:
    build:
      target: production
    env_file:
      - path: ./luvhavencove-store/.env.production
        required: false
    environment:
      - NODE_ENV=production
  storefront:
    env_file:
      - path: ./luvhavencove-store-storefront/.env.production
        required: false
    environment:
      - NODE_ENV=production
secrets:
  cloudflare_api_token.ini:
    file: ./secrets/production/cloudflare_api_token.ini
  meilisearch_master_key:
    file: ./secrets/production/meilisearch_master_key
  paypal_client_secret:
    file: ./secrets/production/paypal_client_secret
  postgres_pass:
    file: ./secrets/production/postgres_pass
  redis.conf:
    file: ./secrets/production/redis.conf
