services:
  nginx:
    depends_on:
      backend:
        condition: service_healthy
      storefront:
        condition: service_started
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    healthcheck:
      test: service nginx status || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-var:/var/lib/letsencrypt
      - webroot:/var/www/_letsencrypt
      - nginx:/etc/nginx
    develop:
      watch:
        - path: ./nginx/nginx
          target: /etc/nginx
          action: sync+restart
    networks:
      - nginx
  backend:
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
      meilisearch:
        condition: service_healthy
        required: true
    build:
      context: ./luvhavencove-store
      dockerfile: Dockerfile
    command: ./run.sh $ENV
    ports:
      - "7001:7001"
      - "9000:9000"
    env_file:
      - path: ./luvhavencove-store/.env
        required: true
    environment:
      - MEILISEARCH_API_KEY_FILE=/run/secrets/meilisearch_master_key
    secrets:
      - meilisearch_master_key
    healthcheck:
      test: >
        curl --fail http://localhost:9000/health || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s
    volumes:
      - public_data:/data/public
      - shared_data:/data/shared
    develop:
      watch:
        - path: ./luvhavencove-store
          action: rebuild
    networks:
      - nginx
  storefront:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ./luvhavencove-store-storefront
      dockerfile: Dockerfile
    command: ./run.sh $ENV
    ports:
      - "8000:8000"
    env_file:
      - path: ./luvhavencove-store-storefront/.env
        required: true
    environment:
      - NEXT_PUBLIC_STRIPE_KEY=/run/secrets/stripe_public_key
    secrets:
      - stripe_public_key
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    volumes:
      - public_data:/data/public
    develop:
      watch:
        - path: ./luvhavencove-store-storefront
          action: rebuild
    networks:
      - nginx
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d luvhavencove
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pass
      - POSTGRES_DB=luvhavencove
    secrets:
      - postgres_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nginx
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server /run/secrets/redis.conf
    secrets:
      - redis.conf
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
    volumes:
      - redisdata:/data
    networks:
      - nginx
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 5s
    environment:
      - MEILISEARCH_MASTER_KEY=/run/secrets/meilisearch_master_key
    secrets:
      - meilisearch_master_key
    command: >
      /bin/sh -c "meilisearch --master-key=$(cat $$MEILISEARCH_MASTER_KEY)"
    volumes:
      - public_data:/data/public
      - shared_data:/data/shared
    networks:
      - nginx
  
volumes:
  nginx:
  pgdata:
  redisdata:
  shared_data:
  public_data:
  letsencrypt-etc:
  letsencrypt-var:
  webroot:
secrets:
  cloudflare_api_token:
    file: ./docker/secrets/cloudflare_api_token.ini
  meilisearch_master_key:
    file: ./docker/secrets/meilisearch_master_key
  paypal_client_id:
    file: ./docker/secrets/paypal_client_id
  paypal_client_secret:
    file: ./docker/secrets/paypal_client_secret
  paypal_auth_webhook_id:
    file: ./docker/secrets/paypal_auth_webhook_id
  postgres_pass:
    file: ./docker/secrets/postgres_pass
  redis.conf:
    file: ./docker/secrets/redis.conf
  stripe_public_key:
    file: ./docker/secrets/stripe_public_key
networks:
  nginx:
    driver: "bridge"
